# [START app_yaml]
runtime: nodejs12

# update with Redis instance details
env_variables:
  REDISHOST: "10.0.1.19"
  REDISPORT: "6379"
  PRODUCTION: 1

resources:
  cpu: 1
  memory_gb: 0.5

automatic_scaling:
  max_instances: 1
  min_instances: 0
  
# update with Redis instance network name
network:
  name: default
# [END app_yaml]