/*
 * Author: Duncan Levings
 * 
 * Copyright (c) 2020 DuncanLevings
 */

// IEMS

export const GET_BRONZE_MAN_ITEMS = 'GET_BRONZE_MAN_ITEMS';
export const GET_BRONZE_MAN_ITEMS_SUCCESS = 'GET_BRONZE_MAN_ITEMS_SUCCESS';

export const SET_ACQUIRED = 'SET_ACQUIRED';
export const SET_ACQUIRED_SUCCESS = 'SET_ACQUIRED_SUCCESS';

export const CREATE_BRONZE_MAN_ITEM = 'CREATE_BRONZE_MAN_ITEM';
export const CREATE_BRONZE_MAN_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';

export const DELETE_BRONZE_MAN_ITEM = 'DELETE_BRONZE_MAN_ITEM';
export const DELETE_BRONZE_MAN_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';

// ERROR

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const ERROR = 'ITEM_ERROR';