/*
 * Author: Duncan Levings
 * 
 * Copyright (c) 2020 DuncanLevings
 */

export const GET_DAILY = 'GET_DAILY';
export const GET_DAILY_SUCCESS = 'GET_DAILY_SUCCESS';
export const SEARCH_DAILY = 'SEARCH_DAILY';
export const SEARCH_DAILY_SUCCESS = 'SEARCH_DAILY_SUCCESS';
export const ADD_DAILY = 'ADD_DAILY';
export const ADD_DAILY_SUCCESS = 'ADD_DAILY_SUCCESS';
export const HIDE_DAILY = 'HIDE_DAILY';
export const HIDE_DAILY_SUCCESS = 'HIDE_DAILY_SUCCESS';
export const CREATE_DAILY = 'CREATE_DAILY';
export const CREATE_DAILY_SUCCESS = 'CREATE_DAILY_SUCCESS';
export const EDIT_DAILY = 'EDIT_DAILY';
export const EDIT_DAILY_SUCCESS = 'EDIT_DAILY_SUCCESS';
export const DELETE_DAILY = 'DELETE_DAILY';
export const DELETE_DAILY_SUCCESS = 'DELETE_DAILY_SUCCESS';
export const REORDER_DAILY = 'REORDER_DAILY';
export const REORDER_DAILY_SUCCESS = 'REORDER_DAILY_SUCCESS';
export const SET_DAILY_TYPE = 'SET_DAILY_TYPE';
export const ERROR = 'DAILY_ERROR';